### ISSUE TITLE
用到babel-loader的报错了。。

### ISSUE THREAD

**Issue by unclechen** [ruanyf/webpack-demos#59]
➜  demo03 git:(master) webpack-dev-server
 http://localhost:8080/webpack-dev-server/
webpack result is served from /
content is served from /Users/noughtchen/mydev/ReactJs/ohehe/webpack-demos/demo03
Hash: 396f0bfb9d565b6f60f0
Version: webpack 1.14.0
Time: 663ms

ERROR in ./main.jsx
Module build failed: Error: Plugin 19 specified in "/Users/noughtchen/mydev/ReactJs/ohehe/webpack-demos/node_modules/babel-preset-es2015/index.js" provided an invalid property of "__esModule"
    at Plugin.init (/Users/noughtchen/mydev/ReactJs/ohehe/webpack-demos/node_modules/babel-core/lib/transformation/plugin.js:124:13)
    at Function.normalisePlugin (/Users/noughtchen/mydev/ReactJs/ohehe/webpack-demos/node_modules/babel-core/lib/transformation/file/options/option-manager.js:155:12)
    at /Users/noughtchen/mydev/ReactJs/ohehe/webpack-demos/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (native)
    at Function.normalisePlugins (/Users/noughtchen/mydev/ReactJs/ohehe/webpack-demos/node_modules/babel-core/lib/transformation/file/options/option-manager.js:161:20)
    at OptionManager.mergeOptions (/Users/noughtchen/mydev/ReactJs/ohehe/webpack-demos/node_modules/babel-core/lib/transformation/file/options/option-manager.js:254:36)
    at OptionManager.mergePresets (/Users/noughtchen/mydev/ReactJs/ohehe/webpack-demos/node_modules/babel-core/lib/transformation/file/options/option-manager.js:308:16)
    at OptionManager.mergeOptions (/Users/noughtchen/mydev/ReactJs/ohehe/webpack-demos/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:12)
    at OptionManager.init (/Users/noughtchen/mydev/ReactJs/ohehe/webpack-demos/node_modules/babel-core/lib/transformation/file/options/option-manager.js:396:10)
    at File.initOptions (/Users/noughtchen/mydev/ReactJs/ohehe/webpack-demos/node_modules/babel-core/lib/transformation/file/index.js:191:75)
webpack: bundle is now VALID.

**Comment by sjq597** [comment]
我也是出现这个问题了，不过我换了一个版本就好了,babel-core换成6.8.0就没这个问题了

**Comment by unclechen** [comment]
@sjq597 非常感谢，修改了babel-core版本，重新npm install，然后进入demo03运行webpack-dev-server就好了。
