### ISSUE TITLE
demo 13 error

### ISSUE THREAD

**Issue by airowgao** [ruanyf/webpack-demos#83]
demo 13 

```
/usr/local/lib/node_modules/webpack/lib/Chunk.js:49
                throw new Error("Chunk.entry was removed. Use hasRuntime()");
                ^

Error: Chunk.entry was removed. Use hasRuntime()
    at Chunk.get entry [as entry] (/usr/local/lib/node_modules/webpack/lib/Chunk.js:49:9)
    at Compilation.processCommonChunk (/Users/gaomin/Desktop/webpack-demos-master/node_modules/webpack/lib/optimize/CommonsChunkPlugin.js:82:21)
    at Array.forEach (native)
    at Compilation.<anonymous> (/Users/gaomin/Desktop/webpack-demos-master/node_modules/webpack/lib/optimize/CommonsChunkPlugin.js:67:17)
    at Compilation.applyPluginsBailResult1 (/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:140:27)
    at Compilation.seal (/usr/local/lib/node_modules/webpack/lib/Compilation.js:601:9)
    at applyPluginsParallel.err (/usr/local/lib/node_modules/webpack/lib/Compiler.js:508:17)
    at /usr/local/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/usr/local/lib/node_modules/webpack/lib/Compilation.js:507:11)
    at processModuleDependencies.err (/usr/local/lib/node_modules/webpack/lib/Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

```

**Comment by ruanyf** [comment]
应该是 Webpack 版本升级了。你是装的 1.x 版吗？

**Comment by airowgao** [comment]
3.8.1
 
------------------ Original ------------------
